# Generated by Django 4.2 on 2023-04-30 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0002_worker_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='worker_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='worker',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workers.worker_company'),
        ),
    ]
